name: random-string-generator
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v2
      - name: install and build
        uses: npm ci
      - name: publish to registry
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registery-url: 'https://npm.pkg.github.com'
          scope: '@nnnpawar7'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
